### ISSUE TITLE
Server error when running locally

### ISSUE THREAD

**Issue by peteruithoven** [jguddas/lucide-studio#3]
While trying to fixing https://github.com/jguddas/lucide-studio/issues/2 I tried running the project locally. 

After a `npm install`, `volta install pnpm` and `npm run dev`, it starts. 
But when I click the Sign in with Github button I get a server error.
![Screenshot from 2024-10-12 16 18 08@2x](https://github.com/user-attachments/assets/4b21ccf3-a57d-4f4b-a29f-eb061c3075fe)
![Screenshot from 2024-10-12 16 18 01@2x](https://github.com/user-attachments/assets/3ebcc5f5-49f3-43dd-8cfa-b0d378772f84)

The following error is shown in logs:
```
 ✓ Compiled /api/auth/[...nextauth] in 3.8s (1595 modules)
[auth][error] TypeError: "ikm"" must be an instance of Uint8Array or a string
    at normalizeUint8Array (webpack-internal:///(rsc)/./node_modules/@panva/hkdf/dist/web/index.js:21:47)
    at normalizeIkm (webpack-internal:///(rsc)/./node_modules/@panva/hkdf/dist/web/index.js:25:17)
    at hkdf (webpack-internal:///(rsc)/./node_modules/@panva/hkdf/dist/web/index.js:47:98)
    at getDerivedEncryptionKey (webpack-internal:///(rsc)/./node_modules/@auth/core/jwt.js:147:67)
    at encode (webpack-internal:///(rsc)/./node_modules/@auth/core/jwt.js:65:36)
    at signCookie (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/actions/callback/oauth/checks.js:34:69)
    at Object.create (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/actions/callback/oauth/checks.js:52:30)
    at async getAuthorizationUrl (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/actions/signin/authorization-url.js:66:39)
    at async Module.signIn (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/actions/signin/index.js:19:60)
    at async AuthInternal (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/index.js:73:24)
 ⨯ src/components/SvgPreview/getPatternMatches.ts (21:25) @ isSubsetOf
 ⨯ TypeError: pattern.vectors.isSubsetOf is not a function
    at getPatternMatches (./src/components/SvgPreview/getPatternMatches.ts:22:30)
    at eval (./src/components/SvgPreview/index.tsx:570:28)
  19 |   const output: { patternName: string; paths: Path[] }[] = [];
  20 |   for (const [patternName, pattern] of patterns) {
> 21 |     if (!pattern.vectors.isSubsetOf(vectorSet)) continue;
     |                         ^
  22 |
  23 |     for (let i = 0; i < paths.length * 2; i++) {
  24 |       if (!pattern.vectors.has(vectors[Math.floor(i / 2)])) continue;
```

I assume I need to do some kind of configuration to make Github sign in possible?

**Comment by peteruithoven** [comment]
I assume I'm missing some env variables. Maybe you can add an `.env.example` file?

**Comment by jguddas** [comment]
I have added a `.env.example` file, still not perfect, but it's a start.
